---
title: "Homework 9 (Week 11)"
author: "Zeyu Wang/Charlie"
date: "March 31, 2019"
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

### Problem 1

#### Sources:
##### Liu, Lin, et al. "Comparison of next-generation sequencing systems." BioMed Research International 2012 (2012).
##### Leggett, Richard M., and Matthew D. Clark. "A world of opportunities with nanopore sequencing." Journal of Experimental Botany 68.20 (2017): 5419-5429.
##### Jain, Miten, et al. "The Oxford Nanopore MinION: delivery of nanopore sequencing to the genomics community." Genome biology 17.1 (2016): 239.

#### 1.1 Summary in one sentence

##### By inserting a nanopore protein into a membrane, with applying voltage across the membrane, a single strand of dsDNA molecular can go through the pore with the help of a motor protein, which will leads to disruptions in the current and can be used to measure the bases, or other features.

#### 1.2 Label the image

*1a dsDNA
*1b single strand of dsDNA
*2 motor protein that helps the strand to go through the pore
*3 artificial membrane
*4 nanopore protein


#### 1.3 Two properties

* It should be able to tolerate extraordinary voltage up to 100mV with current 100pA.
* It should have a pore that can let a dsDNA pass through and help ion exchange.


#### 1.4 The change of current registered (I'm confused with this question)
##### There are microscaffolds which each support a membrane and embedded nanopore, and they correspond to an electrode connected to a channel in the sensor array chip.

#### 1.5 Naturally occuring types of proteins that could be used for the motor protein 

##### The functions of the motor protein should be both unwinding and pass the DNA through the pore, which are functions of helicase and transporter. We need proteins with these type of properities to deal with the process in nanopore sequencing.

#### 1.6 Functions of three adapters

* Facilitating strand capture and loading of a processive enzyme at the 5′-end of one strand
* Concentrating DNA substrates at the membrane surface proximal to the nanopore, boosting the DNA capture rate by several thousand-fold
* Permitting contiguous sequencing of both strands of a duplex molecule by covalently attaching one strand to the other


### Problem 2

#### Advantages:

* Much longer reads, since nanopore sequencing only needs to cut down whole genome once
* More facilitate sequencing, it's portable to lots of places

#### Disadvantages:

* Higher error rates, it's about 10% while Illumina has lower than 1% error rate
* It's sensitive when sequencing, and core parts cannot reuse for much time, which leads to higher cost.



### Problem 3

#### 3.1 Fastqc nanopore sequecing result
```{}

mkdir hw9
cd hw9

for i in `ls  /home/frd2007/ANGSD_2019/nanopore_seq/guppy_out/*.fastq.gz`; do zcat ${i} > .nano_all.fastq; done
gzip -f nano_all.fastq

spack load fastqc
fastqc --extract nano_all.fastq.gz -o .

cd ..
paste hw4/ERR458878_fastqc/summary.txt hw9/nano_all_fastqc/summary.txt | cut -f 1-2,4-5

```

##### Result:
Illumina                     | Nanopore
-----------------------------|------------------------------
PASS    Basic Statistics     |   PASS    Basic Statistics
PASS    Per base sequence quality    |   FAIL    Per base sequence quality
FAIL    Per tile sequence quality     |  NA
PASS    Per sequence quality scores    | WARN    Per sequence quality scores
FAIL    Per base sequence content   |    FAIL    Per base sequence content
PASS    Per sequence GC content | WARN    Per sequence GC content
PASS    Per base N content      | PASS    Per base N content
PASS    Sequence Length Distribution   | WARN    Sequence Length Distribution
WARN    Sequence Duplication Levels     |PASS    Sequence Duplication Levels
PASS    Overrepresented sequences       |PASS    Overrepresented sequences
PASS    Adapter Content | PASS    Adapter Content


#### 3.2 Differences between nanopore and Illumina
* Illumina has a much better result in "Per base sequence quality" than Nanopore, but that may not only because of lower error rate, but may also because we didn't finish running nanopore that day.
* QC result of Illumina contains more aspects than that of Nanopore, which is "Per tile sequence quality" here, but also this may be caused by the unfinished nanopore result.

